services:
  discord-bot:
    container_name: ags_helper_bot
    image: 'python:3.11-slim'
    working_dir: /app
    volumes:
      - '/data/Dbots/AGSHelperBot:/app'
    command: "sh -c \"pip install --no-cache-dir -r requirements.txt && python -u src/main.py\"\n"
    restart: always
    environment:
      - 'DISCORD_TOKEN=${DISCORD_TOKEN}'
      - 'BACKUP_ROOT_FOLDER_ID=${BACKUP_ROOT_FOLDER_ID}'
