services:
  discord-bot:
    container_name: ags_helper_bot
    image: 'python:3.11-slim'
    working_dir: /app
    volumes:
      - '/data/Dbots/AGSHelperBot:/app'
    command: "sh -c \"pip install --no-cache-dir -r requirements.txt && python -u src/main.py\""
    restart: always
    environment:
      - 'DISCORD_TOKEN=${DISCORD_TOKEN}'
      - 'BACKUP_ROOT_FOLDER_ID=${BACKUP_ROOT_FOLDER_ID}'

  dashboard:
    container_name: ags_dashboard
    build:
      context: /data/Dbots/AGSHelperBot/dashboard
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ags-dashboard.rule=Host(`captionato.cloud`)" # Or dash.captionato.cloud based on your DNS
      - "traefik.http.routers.ags-dashboard.entrypoints=web"
      - "traefik.http.services.ags-dashboard.loadbalancer.server.port=3000"
    volumes:
      - '/data/Dbots/AGSHelperBot/data:/app/data'
    restart: always
    environment:
      - 'DATA_DIR=/app/data'
